DROP TRIGGER IF EXISTS `%TABLE_PREFIX%ticket_event_AINS`;
DROP VIEW IF EXISTS `%TABLE_PREFIX%EquipmentFormView`;
DROP VIEW IF EXISTS `%TABLE_PREFIX%EquipmentTicketView`;
DROP TRIGGER IF EXISTS `%TABLE_PREFIX%equipment_status_ADEL`;
DROP TRIGGER IF EXISTS `%TABLE_PREFIX%equipment_status_AUPD`;
DROP TRIGGER IF EXISTS `%TABLE_PREFIX%equipment_status_AINS`;
DROP TRIGGER IF EXISTS `%TABLE_PREFIX%equipment_AUPD`;
DROP TRIGGER IF EXISTS `%TABLE_PREFIX%equipment_AINS`;
DROP TRIGGER IF EXISTS `%TABLE_PREFIX%equipment_ADEL`;
CREATE PROCEDURE IF EXISTS `%TABLE_PREFIX%CreateEquipmentFormFields`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%equipment_ticket`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%equipment_status`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%equipment_category`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%equipment`;



