<?php

namespace model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-03 at 15:50:07.
 */
class EquipmentTicketTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var EquipmentTicket
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EquipmentTicket;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers model\EquipmentTicket::getJsonProperties
     * @todo   Implement testGetJsonProperties().
     */
    public function testGetJsonProperties() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentTicket::getEquipment_id
     * @todo   Implement testGetEquipment_id().
     */
    public function testGetEquipment_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentTicket::getEquipment
     * @todo   Implement testGetEquipment().
     */
    public function testGetEquipment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentTicket::getTicket_id
     * @todo   Implement testGetTicket_id().
     */
    public function testGetTicket_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentTicket::getTicket
     * @todo   Implement testGetTicket().
     */
    public function testGetTicket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentTicket::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentTicket::getAllEquipment
     * @todo   Implement testGetAllEquipment().
     */
    public function testGetAllEquipment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentTicket::getAllTickets
     * @todo   Implement testGetAllTickets().
     */
    public function testGetAllTickets() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentTicket::findByEquipmentId
     * @todo   Implement testFindByEquipmentId().
     */
    public function testFindByEquipmentId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentTicket::findByTicketId
     * @todo   Implement testFindByTicketId().
     */
    public function testFindByTicketId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
