<?php

namespace model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-03 at 15:37:40.
 */
class EquipmentTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Equipment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Equipment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers model\Equipment::getJsonProperties
     * @todo   Implement testGetJsonProperties().
     */
    public function testGetJsonProperties() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getEquipment_id
     * @todo   Implement testGetEquipment_id().
     */
    public function testGetEquipment_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getAsset_id
     * @todo   Implement testGetAsset_id().
     */
    public function testGetAsset_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getCategory_id
     * @todo   Implement testGetCategory_id().
     */
    public function testGetCategory_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getStatus_id
     * @todo   Implement testGetStatus_id().
     */
    public function testGetStatus_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getIspublished
     * @todo   Implement testGetIspublished().
     */
    public function testGetIspublished() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getUpdated
     * @todo   Implement testGetUpdated().
     */
    public function testGetUpdated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getIs_active
     * @todo   Implement testGetIs_active().
     */
    public function testGetIs_active() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getCategory
     * @todo   Implement testGetCategory().
     */
    public function testGetCategory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getUser_id
     * @todo   Implement testGetUser_id().
     */
    public function testGetUser_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getUser
     * @todo   Implement testGetUser().
     */
    public function testGetUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getStaff_id
     * @todo   Implement testGetStaff_id().
     */
    public function testGetStaff_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getStaff
     * @todo   Implement testGetStaff().
     */
    public function testGetStaff() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::setId
     * @todo   Implement testSetId().
     */
    public function testSetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::setEquipment_id
     * @todo   Implement testSetEquipment_id().
     */
    public function testSetEquipment_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::setAsset_id
     * @todo   Implement testSetAsset_id().
     */
    public function testSetAsset_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::setCategory_id
     * @todo   Implement testSetCategory_id().
     */
    public function testSetCategory_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::setStatus_id
     * @todo   Implement testSetStatus_id().
     */
    public function testSetStatus_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::setIspublished
     * @todo   Implement testSetIspublished().
     */
    public function testSetIspublished() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::setCreated
     * @todo   Implement testSetCreated().
     */
    public function testSetCreated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::setUpdated
     * @todo   Implement testSetUpdated().
     */
    public function testSetUpdated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::setIs_active
     * @todo   Implement testSetIs_active().
     */
    public function testSetIs_active() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::setUser_id
     * @todo   Implement testSetUser_id().
     */
    public function testSetUser_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::setStaff_id
     * @todo   Implement testSetStaff_id().
     */
    public function testSetStaff_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getOpenTickets
     * @todo   Implement testGetOpenTickets().
     */
    public function testGetOpenTickets() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getClosedTickets
     * @todo   Implement testGetClosedTickets().
     */
    public function testGetClosedTickets() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getTicketList
     * @todo   Implement testGetTicketList().
     */
    public function testGetTicketList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::assignTicket
     * @todo   Implement testAssignTicket().
     */
    public function testAssignTicket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::onCloseTicket
     * @todo   Implement testOnCloseTicket().
     */
    public function testOnCloseTicket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::countPublishedEquipment
     * @todo   Implement testCountPublishedEquipment().
     */
    public function testCountPublishedEquipment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::findIdByAssetId
     * @todo   Implement testFindIdByAssetId().
     */
    public function testFindIdByAssetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::findByStaffId
     * @todo   Implement testFindByStaffId().
     */
    public function testFindByStaffId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::findByNotStaffId
     * @todo   Implement testFindByNotStaffId().
     */
    public function testFindByNotStaffId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::findByStatusAndCategory
     * @todo   Implement testFindByStatusAndCategory().
     */
    public function testFindByStatusAndCategory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::search
     * @todo   Implement testSearch().
     */
    public function testSearch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::findByAssetId
     * @todo   Implement testFindByAssetId().
     */
    public function testFindByAssetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::findIdByTicket
     * @todo   Implement testFindIdByTicket().
     */
    public function testFindIdByTicket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getTicketFormId
     * @todo   Implement testGetTicketFormId().
     */
    public function testGetTicketFormId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::deleteByTicket
     * @todo   Implement testDeleteByTicket().
     */
    public function testDeleteByTicket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::findByTicket
     * @todo   Implement testFindByTicket().
     */
    public function testFindByTicket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::postSave
     * @todo   Implement testPostSave().
     */
    public function testPostSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::saveDynamicData
     * @todo   Implement testSaveDynamicData().
     */
    public function testSaveDynamicData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\Equipment::getDynamicData
     * @todo   Implement testGetDynamicData().
     */
    public function testGetDynamicData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
