<?php

namespace model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-03 at 15:49:57.
 */
class EquipmentStatusTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var EquipmentStatus
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EquipmentStatus;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers model\EquipmentStatus::getJsonProperties
     * @todo   Implement testGetJsonProperties().
     */
    public function testGetJsonProperties() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::getStatus_id
     * @todo   Implement testGetStatus_id().
     */
    public function testGetStatus_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::getImage
     * @todo   Implement testGetImage().
     */
    public function testGetImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::getColor
     * @todo   Implement testGetColor().
     */
    public function testGetColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::getBaseline
     * @todo   Implement testGetBaseline().
     */
    public function testGetBaseline() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::setStatus_id
     * @todo   Implement testSetStatus_id().
     */
    public function testSetStatus_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::setName
     * @todo   Implement testSetName().
     */
    public function testSetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::setImage
     * @todo   Implement testSetImage().
     */
    public function testSetImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::setColor
     * @todo   Implement testSetColor().
     */
    public function testSetColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::setBaseline
     * @todo   Implement testSetBaseline().
     */
    public function testSetBaseline() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::getBaselineStatus
     * @todo   Implement testGetBaselineStatus().
     */
    public function testGetBaselineStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::save
     * @todo   Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::getEquipment
     * @todo   Implement testGetEquipment().
     */
    public function testGetEquipment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::countEquipment
     * @todo   Implement testCountEquipment().
     */
    public function testCountEquipment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentStatus::countEquipmentByCategory
     * @todo   Implement testCountEquipmentByCategory().
     */
    public function testCountEquipmentByCategory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
