<?php

namespace model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-03 at 15:48:46.
 */
class EquipmentDashboardTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var EquipmentDashboard
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EquipmentDashboard;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers model\EquipmentDashboard::getEquipment
     * @todo   Implement testGetEquipment().
     */
    public function testGetEquipment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentDashboard::getCategories
     * @todo   Implement testGetCategories().
     */
    public function testGetCategories() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentDashboard::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentDashboard::getTickets
     * @todo   Implement testGetTickets().
     */
    public function testGetTickets() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentDashboard::setEquipment
     * @todo   Implement testSetEquipment().
     */
    public function testSetEquipment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentDashboard::setCategories
     * @todo   Implement testSetCategories().
     */
    public function testSetCategories() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentDashboard::setStatus
     * @todo   Implement testSetStatus().
     */
    public function testSetStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentDashboard::setTickets
     * @todo   Implement testSetTickets().
     */
    public function testSetTickets() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
