<?php

namespace model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-03 at 15:25:25.
 */
class EquipmentCategoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var EquipmentCategory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EquipmentCategory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers model\EquipmentCategory::getJsonProperties
     * @todo   Implement testGetJsonProperties().
     */
    public function testGetJsonProperties() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getCategory_id
     * @todo   Implement testGetCategory_id().
     */
    public function testGetCategory_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getNotes
     * @todo   Implement testGetNotes().
     */
    public function testGetNotes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getIspublic
     * @todo   Implement testGetIspublic().
     */
    public function testGetIspublic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getUpdated
     * @todo   Implement testGetUpdated().
     */
    public function testGetUpdated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::setCategory_id
     * @todo   Implement testSetCategory_id().
     */
    public function testSetCategory_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::setNotes
     * @todo   Implement testSetNotes().
     */
    public function testSetNotes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::setCreated
     * @todo   Implement testSetCreated().
     */
    public function testSetCreated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::setName
     * @todo   Implement testSetName().
     */
    public function testSetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::setIspublic
     * @todo   Implement testSetIspublic().
     */
    public function testSetIspublic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::setUpdated
     * @todo   Implement testSetUpdated().
     */
    public function testSetUpdated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getOpenTicketCount
     * @todo   Implement testGetOpenTicketCount().
     */
    public function testGetOpenTicketCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getClosedTicketCount
     * @todo   Implement testGetClosedTicketCount().
     */
    public function testGetClosedTicketCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getParent_id
     * @todo   Implement testGetParent_id().
     */
    public function testGetParent_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::setParent_id
     * @todo   Implement testSetParent_id().
     */
    public function testSetParent_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::countOpenTickets
     * @todo   Implement testCountOpenTickets().
     */
    public function testCountOpenTickets() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getTicketList
     * @todo   Implement testGetTicketList().
     */
    public function testGetTicketList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::countClosedTickets
     * @todo   Implement testCountClosedTickets().
     */
    public function testCountClosedTickets() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::countAll
     * @todo   Implement testCountAll().
     */
    public function testCountAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::countEquipment
     * @todo   Implement testCountEquipment().
     */
    public function testCountEquipment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getChildren
     * @todo   Implement testGetChildren().
     */
    public function testGetChildren() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::getEquipment
     * @todo   Implement testGetEquipment().
     */
    public function testGetEquipment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\EquipmentCategory::expose
     * @todo   Implement testExpose().
     */
    public function testExpose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
