<?php

namespace model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-03 at 15:50:12.
 */
class TicketRecurringTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TicketRecurring
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TicketRecurring;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers model\TicketRecurring::getJsonProperties
     * @todo   Implement testGetJsonProperties().
     */
    public function testGetJsonProperties() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::getEquipment_id
     * @todo   Implement testGetEquipment_id().
     */
    public function testGetEquipment_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::getEquipment
     * @todo   Implement testGetEquipment().
     */
    public function testGetEquipment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::getTicket_id
     * @todo   Implement testGetTicket_id().
     */
    public function testGetTicket_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::getTicket
     * @todo   Implement testGetTicket().
     */
    public function testGetTicket() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::getLast_opened
     * @todo   Implement testGetLast_opened().
     */
    public function testGetLast_opened() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::getNext_date
     * @todo   Implement testGetNext_date().
     */
    public function testGetNext_date() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::setId
     * @todo   Implement testSetId().
     */
    public function testSetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::setEquipment_id
     * @todo   Implement testSetEquipment_id().
     */
    public function testSetEquipment_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::setTicket_id
     * @todo   Implement testSetTicket_id().
     */
    public function testSetTicket_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::setLast_opened
     * @todo   Implement testSetLast_opened().
     */
    public function testSetLast_opened() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::setNext_date
     * @todo   Implement testSetNext_date().
     */
    public function testSetNext_date() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::getInterval
     * @todo   Implement testGetInterval().
     */
    public function testGetInterval() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::setInterval
     * @todo   Implement testSetInterval().
     */
    public function testSetInterval() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::getActive
     * @todo   Implement testGetActive().
     */
    public function testGetActive() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::setActive
     * @todo   Implement testSetActive().
     */
    public function testSetActive() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::getInterval_multiplier
     * @todo   Implement testGetInterval_multiplier().
     */
    public function testGetInterval_multiplier() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::setInterval_multiplier
     * @todo   Implement testSetInterval_multiplier().
     */
    public function testSetInterval_multiplier() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::getHRInterval
     * @todo   Implement testGetHRInterval().
     */
    public function testGetHRInterval() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::findByEquipmentId
     * @todo   Implement testFindByEquipmentId().
     */
    public function testFindByEquipmentId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers model\TicketRecurring::findByTicketId
     * @todo   Implement testFindByTicketId().
     */
    public function testFindByTicketId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
